# Generated by Django 6.0 on 2025-12-20 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ThemeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('primary_color', models.CharField(default='#667eea', max_length=7)),
                ('secondary_color', models.CharField(default='#764ba2', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('symptomes', models.TextField()),
                ('diagnostic', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sante.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=100)),
                ('posologie', models.CharField(max_length=100)),
                ('duree', models.CharField(max_length=50)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sante.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MEDECIN', 'Médecin'), ('INFIRMIER', 'Infirmier'), ('ADMIN', 'Administrateur'), ('SECRETAIRE', 'Secrétaire')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='personnel_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_faites', to='sante.utilisateur'),
        ),
        migrations.CreateModel(
            name='RegistreMaladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cas', models.IntegerField()),
                ('date_enregistrement', models.DateField(auto_now_add=True)),
                ('pathologie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sante.pathologie')),
            ],
            options={
                'unique_together': {('pathologie', 'date_enregistrement')},
            },
        ),
    ]
